### ISSUE TITLE
why not \d+ in regex?

### ISSUE THREAD

**Issue by CudaText-addons** [m-messiah/SublimeLinter-contrib-jsonnet-lint#1]
`    regex = r'(?P<filename>.*):(?P<line>[1-9][0-9]*):(?P<col>[1-9][0-9]*)-(?P<end_col>[1-9][0-9]*) (?P<message>.*)'
`

Why not to use `\d+` here for numbers? do you want to skip numbers with leading 0?

**Comment by m-messiah** [comment]
jsonnet-lint does not return numbers with a leading 0. In theory - yes, the regex could be simplified to `\d+`, but in practice there is no difference for the output
